a=input("Enter your Name: ")
b=int(input("How old are you: "))
c=input("Enter your University Name: ")
d=input("Where is your University Campus: ")
e=input("Where do you Live: ")
f=input("Where is your home Country: ")
g=input("Enter your Email: ")
h=int(input("Enter your Phone Number: "))
i=int(input("Enter your Student ID: "))
j=input("Which Course are you Studying: ")
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)